"""
Typed result structures for Quasi‑Monte‑Carlo (QMC) sampling.

This module defines the `SampleResult` TypedDict, which provides a unified
structure for returning samples generated by QMC methods such as Sobol,
Halton, Latin Hypercube Sampling (LHS), and other low‑discrepancy sequences.

The goal is to ensure:
- consistent return format across all QMC algorithms
- compatibility with static type checkers (mypy, Pylance)
- clear programmatic access to sampled points and metadata
- extensibility via the `extra` field
"""

from typing import TypedDict

import numpy as np


class SampleResult(TypedDict):
    """
    Structured result for QMC sampling.

    Keys
    ----
    samples : np.ndarray
        Generated sample points. Shape typically (n_samples, n_dimensions).
        The exact shape depends on the QMC method used.

    method : str
        Name of the sampling method (e.g., "sobol", "halton", "lhs").

    extra : dict
        Additional metadata. May include:
        - "scramble": bool indicating whether scrambling was applied
        - "seed": int random seed used
        - "dim": int dimensionality of the sample space
        - "engine": name of the underlying SciPy QMC engine
        - any other method‑specific information

    Examples
    --------
    >>> result = {
    ...     "samples": np.array([[0.1, 0.7], [0.4, 0.2]]),
    ...     "method": "sobol",
    ...     "extra": {"scramble": True, "dim": 2}
    ... }
    >>> result["samples"].shape
    (2, 2)

    Notes
    -----
    - QMC methods generate low‑discrepancy sequences, which provide
      better space‑filling properties than classical Monte Carlo.
    - The `extra` field allows downstream code to adapt behavior
      depending on the sampling technique and configuration.
    """

    samples: np.ndarray
    method: str
    extra: dict
